export const blogTags = {
    Technology: [
      "AI",
      "Machine Learning",
      "Cybersecurity",
      "Web Development",
      "Blockchain",
      "Gadgets",
      "Software",
      "Programming",
    ],
    "Health & Wellness": [
      "Mental Health",
      "Nutrition",
      "Fitness",
      "Self-Care",
      "Yoga",
      "Healthy Diet",
      "Medical Research",
      "Home Remedies",
    ],
    Finance: [
      "Investing",
      "Cryptocurrency",
      "Personal Finance",
      "Budgeting",
      "Stock Market",
      "Financial Planning",
      "Tax Tips",
      "Savings",
    ],
    Lifestyle: [
      "Minimalism",
      "Fashion",
      "Personal Development",
      "Motivation",
      "Mindfulness",
      "Productivity",
      "Work-Life Balance",
      "Home Decor",
    ],
    Travel: [
      "Adventure",
      "Backpacking",
      "Luxury Travel",
      "Solo Travel",
      "Budget Travel",
      "Travel Tips",
      "Destinations",
      "Cultural Experiences",
    ],
    Education: [
      "Online Learning",
      "E-Learning Platforms",
      "Study Tips",
      "Exams",
      "Career Advice",
      "Scholarships",
      "Self-Improvement",
      "Skill Development",
    ],
    Food: [
      "Vegan",
      "Keto Diet",
      "Desserts",
      "Street Food",
      "Healthy Recipes",
      "Baking",
      "Cooking Tips",
      "International Cuisine",
    ],
    Business: [
      "Entrepreneurship",
      "Startups",
      "Marketing",
      "Sales",
      "E-commerce",
      "Business Strategies",
      "Leadership",
      "Networking",
    ],
    Entertainment: [
      "Movies",
      "TV Shows",
      "Celebrity News",
      "Music",
      "Gaming",
      "Pop Culture",
      "Streaming Platforms",
      "Comics & Anime",
    ],
    Science: [
      "Space Exploration",
      "Physics",
      "Biotechnology",
      "Genetics",
      "Climate Science",
      "AI & Robotics",
      "Chemistry",
      "Medical Research",
    ],
  };
  